particles:
  rgb:
    animation-speed: 0.020
    ring-points: 28
    update-ticks: 1
    trail-rings: 2
    ring-spacing: 0.32
    top-radius: 0.35
    bottom-radius: 0.95
    total-height: 2.0
    size: 1