name: vip
version: '1.0-SNAPSHOT'
main: com.eNeNzik.vip.Vip
bootstrapper: com.eNeNzik.vip.VipBootstrap
api-version: '1.21'
dependencies:
  server:
    SafeLogin:
      required: false
      load: BEFORE
permissions:
  vip.vip:
    description: Allows using VIP features
    default: false
  vip.vip_plus:
    description: Allows using VIP+ features
    default: false
